### ISSUE TITLE
Gallery Functions

### ISSUE THREAD

**Issue by mxm199** [rigon/photo-gallery#42]
Good day to all!
Tell me, the gallery is installed with a regular docker-compose from the project page. 
Version 1.5.1, but I don't see the Delete, Upload function in the web interface.

How do I find these functions at all -
 Show photo location in a map
 Organize photos:
 Upload new photos
 Move photos
 Delete photos
 Easy selection
 Authentication
 Photos timeline with virtual scroll
 View all places from photos in a map
 Search for duplicates
 Tool for renaming files
 
Or are these plans for future releases?

**Comment by rigon** [comment]
Thanks for giving photo-gallery a go 😁
You can view which features are implemented by looking for
checked/unchecked boxes in the feature list. Unchecked boxes are not
implemented, planned for future releases or not released yet.
However the feature "Organize photos" is complete in terms of
implementation, but still lacks on testing and it is very crucial do that
because those features can lead to data loss. I do NOT recommend using it
at all in this point in time, but if you feel comfortable with that you can
test with the image `rigon/photo-gallery:dev`.

If you could provide additional feedback I really appreciate it, by telling
what you did like/dislike or what could be improved. Will allow me to make
this project better for everyone. Thanks a lot!
