### ISSUE TITLE
User interface

### ISSUE THREAD

**Issue by mxm199** [rigon/photo-gallery#43]
Please tell me how to mark images for deletion or transfer to another folder? (1.5.0 dev). It would probably be convenient to implement some kind of checkbox for selecting images. 

And are there any plans to optimize the interface for mobile devices? Currently, when viewing the interface on a phone, not all top line icons are displayed on the screen (theme selection, zoom)

**Comment by rigon** [comment]
With the mouse, you press down where you want to start selecting, drag until where you want to stop, and only release there. The pretended photos should be highlighted. You can do that many times you want, it will add to the selection. If you start the procedure in an already selected photo, it will do the opposite i.e. deselect. Then use the buttons in the toolbar to move or delete.
The selection does not work on Firefox.
Again, I ask you to be careful using those options as they are not well tested and you can loose photos. Please have backups of them in case something goes wrong.

I'm aware the icons become hidden on small devices, this issue is not yet resolved. I think as well it is becoming confusing having so many options up there, I was planning redesigning that bit but I still don't have a good idea.

Thank you very much for your feedback 😃

**Comment by rigon** [comment]
FYI, I just released v1.5.2 that collapses the toolbar icons into a menu for smaller devices. Please give a go :)

**Comment by rigon** [comment]
dev was updated as well.
